apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ny-power.fullname" . }}-pump
type: Opaque
data:
  password: {{ .Files.Get "secrets/mqtt-password" | b64enc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ny-power.fullname" . }}-nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.mqtt.storage.class }}
  labels:
    app: {{ template "ny-power.name" . }}
    chart: {{ template "ny-power.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mqtt.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ny-power.fullname" . }}
  labels:
    app: {{ template "ny-power.name" . }}
    chart: {{ template "ny-power.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ny-power.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ny-power.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ template "ny-power.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ template "ny-power.fullname" . }}-nfs
      containers:
        - name: {{ template "ny-power.fullname" . }}
          image: "{{ .Values.image.repository }}/{{.Values.mqtt.image.name }}:{{.Values.mqtt.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MQTT_PUMP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "ny-power.fullname" . }}-pump
                  key: password
          volumeMounts:
            - name: {{ template "ny-power.fullname" . }}-volume
              mountPath: "/shared"
          ports:
            - containerPort: 80
            - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ny-power.fullname" . }}
  labels:
    app: {{ template "ny-power.name" . }}
    chart: {{ template "ny-power.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
    protocol: TCP
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: {{ template "ny-power.name" . }}
    release: {{ .Release.Name }}
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: {{ template "ny-power.fullname" . }}-post
#   labels:
#     heritage: {{.Release.Service | quote }}
#     release: {{.Release.Name | quote }}
#     chart: {{ template "ny-power.chart" . }}
#   annotations:
#     # This is what defines this resource as a hook. Without this line, the
#     # job is considered part of the release.
#     "helm.sh/hook": post-install
#     "helm.sh/hook-weight": "-5"
#     "helm.sh/hook-delete-policy": hook-succeeded
# spec:
#   template:
#     metadata:
#       name: {{ template "ny-power.fullname" . }}-post
#       labels:
#         heritage: {{.Release.Service | quote }}
#         release: {{.Release.Name | quote }}
#         chart: "{{.Chart.Name}}-{{.Chart.Version}}"
#     spec:
#       restartPolicy: Never
#       containers:
#       - name: post-install-job
#         image: "alpine:3.3"
#         command: ["/bin/sleep","{{default "10" .Values.sleepyTime}}"]
