install: pip install -U tox-travis
language: python
matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.6
      env: TOXENV=flake8
script: cd src && tox
