apiVersion: v1
kind: Service
metadata:
  name: ny-power-mosquitto
  labels:
    app: mqtt
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    name: ny-power-mosquitto
    protocol: TCP
  selector:
    app: mqtt
