{{- if .Values.reportMetrics -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ny-power.fullname" . }}-metricssa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: {{ template "ny-power.fullname" . }}-metricsrole
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ny-power.fullname" . }}-metricsrolebind
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ny-power.fullname" . }}-metricsrole
subjects:
  - kind: ServiceAccount
    name:  {{ template "ny-power.fullname" . }}-metricssa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ny-power.fullname" . }}-metricsrolebindsystem
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ny-power.fullname" . }}-metricsrole
subjects:
  - kind: ServiceAccount
    name:  {{ template "ny-power.fullname" . }}-metricssa
    namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ny-power.fullname" . }}-metrics
spec:
  template:
    metadata:
      name: {{ template "ny-power.fullname" . }}-metrics
    spec:
      serviceAccountName: {{ template "ny-power.fullname" . }}-metricssa
      containers:
        - env:
            - {name: config, value: '{"repository_id":
                "ny-power", "target_runtimes":
                ["Kubernetes Cluster"], "target_services":
                [null], "event_id": "web", "event_organizer":
                "dev-journeys"}'}
            - {name: language, value: ''}
          image: journeycode/kubernetes:latest
          name: ny-power-metrics
          resources:
            limits: {cpu: 100m}
      restartPolicy: Never
{{- end -}}
