apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ny-power.fullname" . }}-mqtt-pump
type: Opaque
data:
  password: {{ .Values.mqtt.secret | trim | b64enc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ny-power.fullname" . }}-mqtt-nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.mqtt.storage.class }}
  labels:
    app: {{ template "ny-power.name" . }}-mqtt
    chart: {{ template "ny-power.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mqtt.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ny-power.fullname" . }}-mqtt
  labels:
    app: {{ template "ny-power.name" . }}-mqtt
    chart: {{ template "ny-power.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ny-power.name" . }}-mqtt
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ny-power.name" . }}-mqtt
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ template "ny-power.fullname" . }}-mqtt-volume
          persistentVolumeClaim:
            claimName: {{ template "ny-power.fullname" . }}-mqtt-nfs
      containers:
        - name: {{ template "ny-power.fullname" . }}-mqtt
          image: "{{ .Values.image.repository }}/{{.Values.mqtt.image.name }}:{{.Values.mqtt.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MQTT_PUMP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "ny-power.fullname" . }}-mqtt-pump
                  key: password
          volumeMounts:
            - name: {{ template "ny-power.fullname" . }}-mqtt-volume
              mountPath: "/shared"
          ports:
            - containerPort: 80
            - containerPort: 1883
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 15
            periodSeconds: 20
{{- if .Values.enable_istio }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "ny-power.fullname" . }}-mqtt
  labels:
    app: {{ template "ny-power.name" . }}-mqtt
    chart: {{ template "ny-power.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "ny-power.name" . }}-mqtt
    release: {{ .Release.Name }}
  servers:
  - port:
      number: 1883
      name: mqtt
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 80
      name: http
      protocol: TCP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "ny-power.fullname" . }}-mqtt
spec:
  hosts:
  - {{ template "ny-power.fullname" . }}-mqtt
  gateways:
  - {{ template "ny-power.fullname" . }}-mqtt
  tcp:
  - match:
    - port: 1883
    route:
    - destination:
        host: {{ template "ny-power.fullname" . }}-mqtt
        port:
          number: 1883
  - match:
    - port: 80
    route:
    - destination:
        host: {{ template "ny-power.fullname" . }}-mqtt
        port:
          number: 80
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ny-power.fullname" . }}-mqtt
  labels:
    app: {{ template "ny-power.name" . }}-mqtt
    chart: {{ template "ny-power.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
    protocol: TCP
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: {{ template "ny-power.name" . }}-mqtt
    release: {{ .Release.Name }}
