apiVersion: v1
kind: Service
metadata:
  name: ny-power-mqtt
  labels:
    app: mqtt
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    name: ny-power-mqtt
    protocol: TCP
  - port: 1884
    targetPort: 1884
    name: ny-power-websocket
    protocol: TCP
  selector:
    app: mqtt
