apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ny-power-mqtt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      volumes:
      - name: mqtt-state-volume
        persistentVolumeClaim:
          claimName: mqtt-nfs
      containers:
      - name: ny-power-mqtt
        image: registry.ng.bluemix.net/sdague/ny-power-mqtt
        env:
          - name: MQTT_PUMP_PASS
            valueFrom:
              secretKeyRef:
                name: mqtt-pump-secret
                key: password
        volumeMounts:
          - name: mqtt-state-volume
            mountPath: "/shared"
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
        - containerPort: 80
