apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ny-power-influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: influxdb-state-volume
        persistentVolumeClaim:
          claimName: influxdb-nfs
      containers:
      - name: ny-power-mqtt
        image: registry.ng.bluemix.net/sdague/ny-power-influxdb
        volumeMounts:
          - name: influxdb-state-volume
            mountPath: "/data"
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
