apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ny-power-mqtt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: mqtt-pump-secret
      containers:
      - name: ny-power-mqtt
        image: registry.ng.bluemix.net/sdague/ny-power-mqtt
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
