apiVersion: v1
kind: Service
metadata:
  name: ny-power-api
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    name: ny-power-api
    protocol: TCP
  selector:
    app: api
