apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ny-power-pump
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pump
    spec:
      containers:
      - name: ny-power-pump
        image: registry.ng.bluemix.net/sdague/ny-power-pump
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST
          value: ny-power-mqtt
        - name: MQTT_PUMP_PASS
          valueFrom:
            secretKeyRef:
              name: mqtt-pump-secret
              key: password
