apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ny-power-static
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: ny-power-static
        image: registry.ng.bluemix.net/sdague/ny-power-static
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: INFLUXDB_HOST
            value: ny-power-influxdb
          - name: MQTT_HOST
            value: mqtt.ny-power.org
          - name: MQTT_PUMP_PASS
            valueFrom:
              secretKeyRef:
                name: mqtt-pump-secret
                key: password
