apiVersion: batch/v1
kind: Job
metadata:
  name: ny-power-backlog
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: backlog
    spec:
      containers:
      - name: ny-power-backlog
        image: registry.ng.bluemix.net/sdague/ny-power-backlog
        command: ["/usr/local/bin/ny-power-backlog"]
        env:
        - name: INFLUXDB_HOST
          value: ny-power-influxdb
      restartPolicy: Never
