apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ny-power-archive
spec:
  # we have multiple replicas to avoid missing anything
  replicas: 1
  template:
    metadata:
      labels:
        app: archive
    spec:
      containers:
      - name: ny-power-archive
        image: registry.ng.bluemix.net/sdague/ny-power-archive
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST
          value: ny-power-mqtt
        - name: INFLUXDB_HOST
          value: ny-power-influxdb
        - name: MQTT_PUMP_PASS
          valueFrom:
            secretKeyRef:
              name: mqtt-pump-secret
              key: password
