apiVersion: apps/v1
kind: Deployment
metadata:
  name: ny-power-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      revisionHistoryLimit: 2
      containers:
      - name: ny-power-api
        image: registry.ng.bluemix.net/sdague/ny-power-api:20180218-10
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: INFLUXDB_HOST
            value: ny-power-influxdb
          - name: MQTT_HOST
            value: mqtt.ny-power.org
          - name: MQTT_PUMP_PASS
            valueFrom:
              secretKeyRef:
                name: mqtt-pump-secret
                key: password
